### ISSUE TITLE
Making xptMiner failed:  no matching function for call to 'ceil(double&)'

### ISSUE THREAD

**Issue by renyidong** [dave-andersen/fastrie#2]
```
$ LD_LIBRARY_PATH=/usr/local/lib make
g++ -c -Wall -Wextra -std=c++0x -O3 -fomit-frame-pointer  -g -march=native -I/usr/local/include -I/usr/include -IxptMiner/includes/ -IxptMiner/OpenCL xptMiner/riecoinMiner.cpp -o xptMiner/riecoinMiner.o 
xptMiner/riecoinMiner.cpp: In function 'void riecoin_init(uint64_t, int)':
xptMiner/riecoinMiner.cpp:180: error: no matching function for call to 'ceil(double&)'
xptMiner/riecoinMiner.cpp: In function 'void verify_thread()':
xptMiner/riecoinMiner.cpp:489: warning: comparison between signed and unsigned integer expressions
make: *** [xptMiner/riecoinMiner.o] Error 1
```

I'm making on a CentOS6, with epel, and compiled gmp-5.1.3 same as in README .
Though making on another machine with Debian testing has no problem. So I guess this is caused by an old library. 

Can anyone tell me which library should I take a look, or if anyone knows where can I get optimized source? Pre-built binaries makes segment fault on my computer.

**Comment by carlbennett** [comment]
I am having this error as well.

**Comment by renyidong** [comment]
Hey @carlbennett , It has been quite a while since I opened the issue. Many things could have changed. Your issue might not be the same as mine. Maybe you should open another issue (with your log).
